### ISSUE TITLE
Problem running zanzibar init

### ISSUE THREAD

**Issue by rnowosielski** [Cimpress-MCP/zanzibar#14] opened 2015-09-18 09:20 UTC
I am new to this gem so maybe I am doing something wrong, but after installing the gem I am unable to use the `zanzibar init` command

What I did is:

```
E:\workspace\ivbcore>gem install zanzibar
Successfully installed zanzibar-0.1.21
Parsing documentation for zanzibar-0.1.21
Installing ri documentation for zanzibar-0.1.21
Done installing documentation for zanzibar after 0 seconds
1 gem installed

E:\workspace\ivbcore>zanzibar init
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/akami-1.3.1/lib/akami/wsse/verify_signature.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/akami-1.3.1/lib/akami/wsse.rb:9:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/akami-1.3.1/lib/akami.rb:2:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/savon-2.8.1/lib/savon/header.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by maclennann** [comment] 2015-09-18 11:20
It looks like one of our transitive dependencies, nokogiri, [doesn't work under ruby 2.2 on Windows](https://github.com/sparklemotion/nokogiri/issues/1256).

According to the thread, it will be fixed once they take version 1.6.7 out of RC. I'm not sure when that will be, but it looks like the various versions ranges in our dependency chain means we will be able to get this update for free (i.e. we don't have to wait for savon or akami to update as well).

In the meantime, I guess your only options are to use ruby 2.1 or use Linux.

**Comment by flavorjones** [comment] 2015-09-18 12:17
There will be at least one more RC for Nokogiri 1.6.7, and I appreciate everyone's patience. We're adding first-class Windows support, and it hasn't been quick or easy; but hopefully will make people's lives better.

Look for 1.6.7 final within the next week.

**Comment by rnowosielski** [comment] 2015-09-24 15:51
I checked with the RC of nokogiri - it worked fine for me so it seems like a valid workaround for me now.

**Comment by maclennann** [comment] 2015-12-02 14:32
1.6.7 is out of RC and I confirmed that we no longer explode under 2.2/windows

**Closed by maclennann** 2015-12-02 14:32 UTC
